import time
import os
import colorama
from colorama import Fore, Style
print(Fore.RED + ".")

print("Developed")
print("BY")
print("TjGhostMx")

os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
