import time
import os
import colorama
from colorama import Fore, Style
print(Fore.RED + " ")

os.system('clear')
print("Developed By TjGHostMX")
print("Please Wait 5 Seconds")
time.sleep(5)
print("THANK YOU FOR USING MY SCRIPT")
os.system('clear')

os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
os.system('pivpn -c')
time.sleep(300)
print(Fore.RED + ".")
print("===========TJGHOSTMX=============== ")
print(" ")
